<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59356b0fcf1bd',
	'title' => 'Filter Questions',
	'fields' => array (
		array (
			'sub_fields' => array (
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_59356f57fa6e2',
					'label' => 'Text Before',
					'name' => 'text_before',
					'type' => 'text',
					'instructions' => 'Enter text to appear before form control.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'taxonomy' => 'pcff_questions',
					'field_type' => 'select',
					'multiple' => 0,
					'allow_null' => 0,
					'return_format' => 'id',
					'add_term' => 0,
					'load_terms' => 0,
					'save_terms' => 0,
					'key' => 'field_59356f7ff68a0',
					'label' => 'Question',
					'name' => 'pcff_question',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'key' => 'field_59356fb4f68a1',
					'label' => 'Text After',
					'name' => 'text_after',
					'type' => 'text',
					'instructions' => 'Enter text to appear after the form control.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Question',
			'collapsed' => 'field_59356f57fa6e2',
			'key' => 'field_59356b720420a',
			'label' => 'Questions',
			'name' => 'pcff_questions',
			'type' => 'repeater',
			'instructions' => 'Add filter questions',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-questions.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

endif;
